const BIVE_Address = "0x2Fbee4B84918a92097503f7336bDE49a2AAaB58F";
const VRA_Address = "0xc1C2D0754A2d4a0F79F248a0e4E6E9f87e6b0D99";
const BIZ_Address = "0x137bE3Af4357a607Bc4DfEDB0dfd3893AFd21E6D";
const LAB_Address = "0x25a2b3f3435060Be87D57093714C3EB6C7f693Aa";
const LP_Address = "0x917fEEb2374515B2F8E79c605ff79011737D7081";
const ROUTER_Address = "0x76E7C4D54cFF6Dc0f18fE0A3A4f6CC4223464B7A";
const ABI = {
    BIVE: [
        {
            "anonymous":false,
            "inputs":[
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"owner",
                    "type":"address"
                },
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"spender",
                    "type":"address"
                },
                {
                    "indexed":false,
                    "internalType":"uint256",
                    "name":"value",
                    "type":"uint256"
                }
            ],
            "name":"Approval",
            "type":"event"
        },
        {
            "anonymous":false,
            "inputs":[
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"from",
                    "type":"address"
                },
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"to",
                    "type":"address"
                },
                {
                    "indexed":false,
                    "internalType":"uint256",
                    "name":"value",
                    "type":"uint256"
                }
            ],
            "name":"Transfer",
            "type":"event"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"owner",
                    "type":"address"
                },
                {
                    "internalType":"address",
                    "name":"spender",
                    "type":"address"
                }
            ],
            "name":"allowance",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"",
                    "type":"uint256"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"spender",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"amount",
                    "type":"uint256"
                }
            ],
            "name":"approve",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"account",
                    "type":"address"
                }
            ],
            "name":"balanceOf",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"",
                    "type":"uint256"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[

            ],
            "name":"decimals",
            "outputs":[
                {
                    "internalType":"uint8",
                    "name":"",
                    "type":"uint8"
                }
            ],
            "stateMutability":"pure",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"account",
                    "type":"address"
                }
            ],
            "name":"isBlacklist",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[

            ],
            "name":"name",
            "outputs":[
                {
                    "internalType":"string",
                    "name":"",
                    "type":"string"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[

            ],
            "name":"symbol",
            "outputs":[
                {
                    "internalType":"string",
                    "name":"",
                    "type":"string"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[

            ],
            "name":"totalSupply",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"",
                    "type":"uint256"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"recipient",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"amount",
                    "type":"uint256"
                }
            ],
            "name":"transfer",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"sender",
                    "type":"address"
                },
                {
                    "internalType":"address",
                    "name":"recipient",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"amount",
                    "type":"uint256"
                }
            ],
            "name":"transferFrom",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
        }
    ],
    BIZ: [
        {
            "anonymous":false,
            "inputs":[
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"owner",
                    "type":"address"
                },
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"spender",
                    "type":"address"
                },
                {
                    "indexed":false,
                    "internalType":"uint256",
                    "name":"value",
                    "type":"uint256"
                }
            ],
            "name":"Approval",
            "type":"event"
        },
        {
            "anonymous":false,
            "inputs":[
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"from",
                    "type":"address"
                },
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"to",
                    "type":"address"
                },
                {
                    "indexed":false,
                    "internalType":"uint256",
                    "name":"value",
                    "type":"uint256"
                }
            ],
            "name":"Transfer",
            "type":"event"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"owner",
                    "type":"address"
                },
                {
                    "internalType":"address",
                    "name":"spender",
                    "type":"address"
                }
            ],
            "name":"allowance",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"",
                    "type":"uint256"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"spender",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"amount",
                    "type":"uint256"
                }
            ],
            "name":"approve",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"account",
                    "type":"address"
                }
            ],
            "name":"balanceOf",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"",
                    "type":"uint256"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[

            ],
            "name":"decimals",
            "outputs":[
                {
                    "internalType":"uint8",
                    "name":"",
                    "type":"uint8"
                }
            ],
            "stateMutability":"pure",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"account",
                    "type":"address"
                }
            ],
            "name":"isBlacklist",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"target",
                    "type":"address"
                }
            ],
            "name":"isWhitelisted",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[

            ],
            "name":"name",
            "outputs":[
                {
                    "internalType":"string",
                    "name":"",
                    "type":"string"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[

            ],
            "name":"owner",
            "outputs":[
                {
                    "internalType":"address",
                    "name":"",
                    "type":"address"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[

            ],
            "name":"symbol",
            "outputs":[
                {
                    "internalType":"string",
                    "name":"",
                    "type":"string"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[

            ],
            "name":"totalSupply",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"",
                    "type":"uint256"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"recipient",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"amount",
                    "type":"uint256"
                }
            ],
            "name":"transfer",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"sender",
                    "type":"address"
                },
                {
                    "internalType":"address",
                    "name":"recipient",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"amount",
                    "type":"uint256"
                }
            ],
            "name":"transferFrom",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
        }
    ],
    VRA: [
        {
            "anonymous":false,
            "inputs":[
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"owner",
                    "type":"address"
                },
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"spender",
                    "type":"address"
                },
                {
                    "indexed":false,
                    "internalType":"uint256",
                    "name":"value",
                    "type":"uint256"
                }
            ],
            "name":"Approval",
            "type":"event"
        },
        {
            "anonymous":false,
            "inputs":[
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"from",
                    "type":"address"
                },
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"to",
                    "type":"address"
                },
                {
                    "indexed":false,
                    "internalType":"uint256",
                    "name":"value",
                    "type":"uint256"
                }
            ],
            "name":"Transfer",
            "type":"event"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"owner",
                    "type":"address"
                },
                {
                    "internalType":"address",
                    "name":"spender",
                    "type":"address"
                }
            ],
            "name":"allowance",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"",
                    "type":"uint256"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"spender",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"amount",
                    "type":"uint256"
                }
            ],
            "name":"approve",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"account",
                    "type":"address"
                }
            ],
            "name":"balanceOf",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"",
                    "type":"uint256"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[

            ],
            "name":"decimals",
            "outputs":[
                {
                    "internalType":"uint8",
                    "name":"",
                    "type":"uint8"
                }
            ],
            "stateMutability":"pure",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"account",
                    "type":"address"
                }
            ],
            "name":"isBlacklist",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"target",
                    "type":"address"
                }
            ],
            "name":"isWhitelisted",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[

            ],
            "name":"name",
            "outputs":[
                {
                    "internalType":"string",
                    "name":"",
                    "type":"string"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[

            ],
            "name":"owner",
            "outputs":[
                {
                    "internalType":"address",
                    "name":"",
                    "type":"address"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[

            ],
            "name":"symbol",
            "outputs":[
                {
                    "internalType":"string",
                    "name":"",
                    "type":"string"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[

            ],
            "name":"totalSupply",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"",
                    "type":"uint256"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"recipient",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"amount",
                    "type":"uint256"
                }
            ],
            "name":"transfer",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"sender",
                    "type":"address"
                },
                {
                    "internalType":"address",
                    "name":"recipient",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"amount",
                    "type":"uint256"
                }
            ],
            "name":"transferFrom",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
    ],
    LAB: [
        {
            "anonymous":false,
            "inputs":[
                {
                    "indexed":true,
                    "internalType":"uint256",
                    "name":"amountIn",
                    "type":"uint256"
                },
                {
                    "indexed":true,
                    "internalType":"uint256",
                    "name":"amountOut",
                    "type":"uint256"
                }
            ],
            "name":"SwapBIVEToBIZ",
            "type":"event"
        },
        {
            "anonymous":false,
            "inputs":[
                {
                    "indexed":true,
                    "internalType":"uint256",
                    "name":"amount",
                    "type":"uint256"
                }
            ],
            "name":"SwapVRAToBIZ",
            "type":"event"
        },
        {
            "inputs":[
                {
                    "internalType":"uint256",
                    "name":"amountOut",
                    "type":"uint256"
                }
            ],
            "name":"getAmountIn",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"amountIn",
                    "type":"uint256"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"uint256",
                    "name":"amountIn",
                    "type":"uint256"
                }
            ],
            "name":"getAmountOut",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"amountOut",
                    "type":"uint256"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"uint256",
                    "name":"amountInMax",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"amountOut",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"deadline",
                    "type":"uint256"
                }
            ],
            "name":"swapBiveToExactBiz",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"uint256",
                    "name":"amountIn",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"amountOutMin",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"deadline",
                    "type":"uint256"
                }
            ],
            "name":"swapExactBiveToBiz",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"uint256",
                    "name":"amountIn",
                    "type":"uint256"
                }
            ],
            "name":"swapVRA",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"amountOut",
                    "type":"uint256"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
        }
    ],
    ROUTER: [
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"tokenA",
                    "type":"address"
                },
                {
                    "internalType":"address",
                    "name":"tokenB",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"amountADesired",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"amountBDesired",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"amountAMin",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"amountBMin",
                    "type":"uint256"
                },
                {
                    "internalType":"address",
                    "name":"to",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"deadline",
                    "type":"uint256"
                }
            ],
            "name":"addLiquidity",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"amountA",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"amountB",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"liquidity",
                    "type":"uint256"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"token",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"amountTokenDesired",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"amountTokenMin",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"amountETHMin",
                    "type":"uint256"
                },
                {
                    "internalType":"address",
                    "name":"to",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"deadline",
                    "type":"uint256"
                }
            ],
            "name":"addLiquidityETH",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"amountToken",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"amountETH",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"liquidity",
                    "type":"uint256"
                }
            ],
            "stateMutability":"payable",
            "type":"function"
        },
        {
            "inputs":[

            ],
            "name":"factory",
            "outputs":[
                {
                    "internalType":"address",
                    "name":"",
                    "type":"address"
                }
            ],
            "stateMutability":"view",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"uint256",
                    "name":"amountOut",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"reserveIn",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"reserveOut",
                    "type":"uint256"
                }
            ],
            "name":"getAmountIn",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"amountIn",
                    "type":"uint256"
                }
            ],
            "stateMutability":"pure",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"uint256",
                    "name":"amountIn",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"reserveIn",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"reserveOut",
                    "type":"uint256"
                }
            ],
            "name":"getAmountOut",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"amountOut",
                    "type":"uint256"
                }
            ],
            "stateMutability":"pure",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"uint256",
                    "name":"amountA",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"reserveA",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"reserveB",
                    "type":"uint256"
                }
            ],
            "name":"quote",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"amountB",
                    "type":"uint256"
                }
            ],
            "stateMutability":"pure",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"tokenA",
                    "type":"address"
                },
                {
                    "internalType":"address",
                    "name":"tokenB",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"liquidity",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"amountAMin",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"amountBMin",
                    "type":"uint256"
                },
                {
                    "internalType":"address",
                    "name":"to",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"deadline",
                    "type":"uint256"
                }
            ],
            "name":"removeLiquidity",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"amountA",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"amountB",
                    "type":"uint256"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"address",
                    "name":"tokenA",
                    "type":"address"
                },
                {
                    "internalType":"address",
                    "name":"tokenB",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"liquidity",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"amountAMin",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"amountBMin",
                    "type":"uint256"
                },
                {
                    "internalType":"address",
                    "name":"to",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"deadline",
                    "type":"uint256"
                },
                {
                    "internalType":"bool",
                    "name":"approveMax",
                    "type":"bool"
                },
                {
                    "internalType":"uint8",
                    "name":"v",
                    "type":"uint8"
                },
                {
                    "internalType":"bytes32",
                    "name":"r",
                    "type":"bytes32"
                },
                {
                    "internalType":"bytes32",
                    "name":"s",
                    "type":"bytes32"
                }
            ],
            "name":"removeLiquidityWithPermit",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"amountA",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"amountB",
                    "type":"uint256"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"uint256",
                    "name":"amountIn",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"amountOutMin",
                    "type":"uint256"
                },
                {
                    "internalType":"address[]",
                    "name":"path",
                    "type":"address[]"
                },
                {
                    "internalType":"address",
                    "name":"to",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"deadline",
                    "type":"uint256"
                }
            ],
            "name":"swapExactTokensForTokens",
            "outputs":[
                {
                    "internalType":"uint256[]",
                    "name":"amounts",
                    "type":"uint256[]"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "inputs":[
                {
                    "internalType":"uint256",
                    "name":"amountOut",
                    "type":"uint256"
                },
                {
                    "internalType":"uint256",
                    "name":"amountInMax",
                    "type":"uint256"
                },
                {
                    "internalType":"address[]",
                    "name":"path",
                    "type":"address[]"
                },
                {
                    "internalType":"address",
                    "name":"to",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"deadline",
                    "type":"uint256"
                }
            ],
            "name":"swapTokensForExactTokens",
            "outputs":[
                {
                    "internalType":"uint256[]",
                    "name":"amounts",
                    "type":"uint256[]"
                }
            ],
            "stateMutability":"nonpayable",
            "type":"function"
        }
    ],
    LP: [
        {
            "anonymous":false,
            "inputs":[
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"from",
                    "type":"address"
                },
                {
                    "indexed":true,
                    "internalType":"address",
                    "name":"to",
                    "type":"address"
                },
                {
                    "indexed":false,
                    "internalType":"uint256",
                    "name":"value",
                    "type":"uint256"
                }
            ],
            "name":"Transfer",
            "type":"event"
        },
        {
            "constant":true,
            "inputs":[
                {
                    "internalType":"address",
                    "name":"",
                    "type":"address"
                },
                {
                    "internalType":"address",
                    "name":"",
                    "type":"address"
                }
            ],
            "name":"allowance",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"",
                    "type":"uint256"
                }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
        },
        {
            "constant":false,
            "inputs":[
                {
                    "internalType":"address",
                    "name":"spender",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"value",
                    "type":"uint256"
                }
            ],
            "name":"approve",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "constant":true,
            "inputs":[
                {
                    "internalType":"address",
                    "name":"",
                    "type":"address"
                }
            ],
            "name":"balanceOf",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"",
                    "type":"uint256"
                }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
        },
        {
            "constant":true,
            "inputs":[

            ],
            "name":"decimals",
            "outputs":[
                {
                    "internalType":"uint8",
                    "name":"",
                    "type":"uint8"
                }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
        },
        {
            "constant":true,
            "inputs":[

            ],
            "name":"getReserves",
            "outputs":[
                {
                    "internalType":"uint112",
                    "name":"_reserve0",
                    "type":"uint112"
                },
                {
                    "internalType":"uint112",
                    "name":"_reserve1",
                    "type":"uint112"
                },
                {
                    "internalType":"uint32",
                    "name":"_blockTimestampLast",
                    "type":"uint32"
                }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
        },
        {
            "constant":false,
            "inputs":[
                {
                    "internalType":"address",
                    "name":"_token0",
                    "type":"address"
                },
                {
                    "internalType":"address",
                    "name":"_token1",
                    "type":"address"
                }
            ],
            "name":"initialize",
            "outputs":[

            ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "constant":true,
            "inputs":[

            ],
            "name":"kLast",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"",
                    "type":"uint256"
                }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
        },
        {
            "constant":true,
            "inputs":[

            ],
            "name":"name",
            "outputs":[
                {
                    "internalType":"string",
                    "name":"",
                    "type":"string"
                }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
        },
        {
            "constant":true,
            "inputs":[

            ],
            "name":"price0CumulativeLast",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"",
                    "type":"uint256"
                }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
        },
        {
            "constant":true,
            "inputs":[

            ],
            "name":"price1CumulativeLast",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"",
                    "type":"uint256"
                }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
        },
        {
            "constant":true,
            "inputs":[

            ],
            "name":"symbol",
            "outputs":[
                {
                    "internalType":"string",
                    "name":"",
                    "type":"string"
                }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
        },
        {
            "constant":true,
            "inputs":[

            ],
            "name":"totalSupply",
            "outputs":[
                {
                    "internalType":"uint256",
                    "name":"",
                    "type":"uint256"
                }
            ],
            "payable":false,
            "stateMutability":"view",
            "type":"function"
        },
        {
            "constant":false,
            "inputs":[
                {
                    "internalType":"address",
                    "name":"to",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"value",
                    "type":"uint256"
                }
            ],
            "name":"transfer",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function"
        },
        {
            "constant":false,
            "inputs":[
                {
                    "internalType":"address",
                    "name":"from",
                    "type":"address"
                },
                {
                    "internalType":"address",
                    "name":"to",
                    "type":"address"
                },
                {
                    "internalType":"uint256",
                    "name":"value",
                    "type":"uint256"
                }
            ],
            "name":"transferFrom",
            "outputs":[
                {
                    "internalType":"bool",
                    "name":"",
                    "type":"bool"
                }
            ],
            "payable":false,
            "stateMutability":"nonpayable",
            "type":"function"
        }
    ]
};
const tokenList = [BIVE_Address.toLowerCase(), VRA_Address.toLowerCase(), BIZ_Address.toLowerCase(), LP_Address.toLowerCase()];

async function getBalanceToken({address}){
    const options = { chain: "mumbai", order: "desc", from_block: "0", address:address };
    const balanceAll = await Moralis.Web3API.account.getTokenBalances(options);
    const balance = balanceAll.filter((value) => {
        if (tokenList.includes(value.token_address.toLowerCase())) return value
    })
    return balance
}

async function getBalanceNative({address}){
    const options = { chain: "mumbai", order: "desc", from_block: "0", address:address };
    const balance = await Moralis.Web3API.account.getNativeBalance(options);
    return balance;
}

async function getTransaction({address}){
    const options = { chain: "mumbai", order: "desc", from_block: "0", address:address };
    const allTransactions = await Moralis.Web3API.account.getTransactions(options);
    return allTransactions;
}

async function getTransferToken({address}){
    const options = { chain: "mumbai", order: "desc", from_block: "0", address:address };
    const allTransactions = await Moralis.Web3API.account.getTokenTransfers(options);
    const txs = allTransactions.result.filter((value) => {
        if (tokenList.includes(value.address.toLowerCase())) return value
    })
    return txs;
}

async function getAllowance({address}){
    let result = {
        BIVE:{
            LAB: null
        },
        VRA:{
            LAB: null
        },
        LP:{
            ROUTER: null
        }
    };
    const options_BIVE = {
        chain: "mumbai",
        function_name: "allowance",
        abi: ABI.BIVE,
        address:BIVE_Address,
        params: {owner: address, spender: LAB_Address}
    };
    result.BIVE.LAB = await Moralis.Web3API.native.runContractFunction(options_BIVE);
    const options_VRA = {
        chain: "mumbai",
        function_name: "allowance",
        abi: ABI.VRA,
        address:VRA_Address,
        params: {owner: address, spender: LAB_Address}
    };
    result.VRA.LAB = await Moralis.Web3API.native.runContractFunction(options_VRA);
    return result;
}

async function getSwapExactVRAtoBIVE({amountIn}){
    let {_reserve0, _reserve1} = await Moralis.Web3API.native.runContractFunction(
        {
            chain: "mumbai",
            function_name: "getReserves",
            abi: ABI.LP,
            address:LP_Address
        }
    );

    const result = await Moralis.Web3API.native.runContractFunction(
        {
            chain: "mumbai",
            function_name: "getAmountOut",
            abi: ABI.ROUTER,
            address:ROUTER_Address,
            params:{
                amountIn: amountIn,
                reserveIn:_reserve1,
                reserveOut: _reserve0
            }
        }
    );
    return result
}

async function getSwapVRAtoExactBIVE({amountOut}){
    let {_reserve0, _reserve1} = await Moralis.Web3API.native.runContractFunction(
        {
            chain: "mumbai",
            function_name: "getReserves",
            abi: ABI.LP,
            address:LP_Address
        }
    );

    result = {
        amountOut: amountOut,
        reserveIn:_reserve1,
        reserveOut: _reserve0
    }

    // const result = await Moralis.Web3API.native.runContractFunction(
    //     {
    //         chain: "mumbai",
    //         function_name: "getAmountIn",
    //         abi: ABI.ROUTER,
    //         address:ROUTER_Address,
    //         params:{
    //             amountOut: amountOut,
    //             reserveIn:_reserve1,
    //             reserveOut: _reserve0
    //         }
    //     }
    // );
    return result
}
